# Generated by Django 4.2.7 on 2023-11-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_rename_vote_radio_project_vote_ratio"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="feature_image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to=""
            ),
        ),
    ]
