# Generated by Django 4.2.7 on 2023-11-21 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_project_feature_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="feature_image",
            new_name="featured_image",
        ),
    ]
