# Generated by Django 4.2.7 on 2023-12-02 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_alter_project_options_review_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-vote_ratio", "-vote_total", "title"]},
        ),
    ]
